---
- hosts: wodan.home.local
  vars:
    vmdir: /home/bdubois/Documents/Labs
    template_disk: ansible-client-clone.qcow2
    vmnet:
      basemac: 52:54:00:4e:12
      gateway: 192.168.122.1
      dns: 192.168.122.1
      netmask: 255.255.255.0
      domain: home.local
    qemu:
      machine: pc-i440fx-2.3
    vms:
      calamari:
        mac: 00
        cpu: 1
        ip: 192.168.122.44
        mem: 1048576
      mon1:
        mac: 01
        cpu: 1
        ip: 192.168.122.45
        mem: 1048576
      mon2:
        mac: 02
        cpu: 1
        ip: 192.168.122.46
        mem: 1048576
      mon3:
        mac: 03
        cpu: 1
        ip: 192.168.122.47
        mem: 1048576
      osd1:
        mac: 05
        cpu: 2
        ip: 192.168.122.48
        mem: 2097152
        addisk: 20
      osd2:
        mac: 06
        cpu: 2
        ip: 192.168.122.49
        mem: 2097152
        addisk: 20
      osd3:
        mac: 07
        cpu: 2
        ip: 192.168.122.50
        mem: 2097152
        addisk: 20

  tasks:

  - name: create VM Disks
    shell: qemu-img create -f qcow2 -b "{{ template_disk }}" "{{ item.key }}".qcow2 chdir="{{ vmdir }}"
    with_dict: "{{ vms }}"

  - name: inject network-config
    shell: virt-customize -a  "{{ vmdir }}"/"{{ item.key }}".qcow2 --run-command 'echo "{{ lookup('template', 'ifconfig.j2') }}" > /etc/sysconfig/network-scripts/ifcfg-eth0'
    with_dict: "{{ vms }}"

  - name: hostname
    shell: virt-customize -a  "{{ vmdir }}"/"{{ item.key }}".qcow2 --run-command 'echo "{{ lookup('template', 'hostname.j2') }}" > /etc/hostname'
    with_dict: "{{ vms }}"

  - name: create Additional Disks
    shell: qemu-img create -f qcow2 "{{ item.key }}"_addisk.qcow2 "{{ item.value.addisk }}"G chdir="{{ vmdir }}"
    when: item.value.addisk is defined
    with_dict: "{{ vms }}"

  - name: Create VMs
    virt: name={{ item.key }}
          command=define
          xml="{{ lookup('template', 'vm_xml.j2') }}"
    with_dict: "{{ vms }}"

  - name: Start VMs
    virt: name={{ item.key }}
          state=running
    with_dict: "{{ vms }}"
